'use client';
import { useState, useEffect } from 'react';
import * as Sentry from '@sentry/nextjs';

/**
 * Falls back to the rules engine's own per-flag `summary` text when the AI
 * explanation for this category is missing (explanation?.details?.[cat] was
 * undefined — whether because the whole AI explanation failed, or just this
 * one category's entry was absent). `flag.summary` is already a complete,
 * plain-language sentence generated by the rules engine and stored in
 * scan_cache regardless of whether the AI call succeeds, so it's a real,
 * always-available substitute rather than showing nothing.
 *
 * Uses only the first flag's summary, not one paragraph per matched
 * ingredient — a category can carry a dozen+ flags (e.g. conventional_crops)
 * whose summaries are the same template sentence with only the ingredient
 * name swapped, so stacking all of them would read as repetitive noise. One
 * representative sentence, in the same single-paragraph slot the AI
 * explanation normally occupies, matches how the working AI explanation
 * already behaves (one category-level explanation, not one per ingredient) —
 * the ingredient chips above this text already list every matched ingredient.
 *
 * Exported at module scope for direct unit testing — this project has no
 * React rendering test infrastructure (see SwapsScreen.jsx/FLAG_CATEGORY_MAP
 * for the same pattern).
 *
 * @param {object[]} flags
 * @returns {string|null}
 */
export function getFallbackSummary(flags) {
  return flags?.[0]?.summary || null;
}

const CATEGORY_INFO = {
  trans_fats:          { icon: '⛔', label: 'Trans Fats' },
  seed_oils:           { icon: '🫙', label: 'Seed Oils' },
  conventional_crops:  { icon: '🌽', label: 'Conventional Crops' },
  bioengineering:      { icon: '🧬', label: 'Bioengineering' },
  natural_flavors:     { icon: '🍃', label: 'Natural Flavors' },
  additives:           { icon: '🧪', label: 'Additives' },
  synthetic_additives: { icon: '🧪', label: 'Additives' },
  gluten_grains:       { icon: '🌾', label: 'Gluten Grains' },
  glyphosate_heavy:    { icon: '☠️', label: 'High Glyphosate Risk' },
  conventional_meat:   { icon: '🥩', label: 'Conventional Meat' },
  conventional_dairy:  { icon: '🥛', label: 'Conventional Dairy' },
  conventional_eggs:   { icon: '🥚', label: 'Conventional Eggs', description: 'Eggs from conventionally raised hens, which may be exposed to pesticide-laden feed and crowded conditions.' },
  fortified_vitamins:  { icon: '💊', label: 'Synthetic Fortification', description: 'Synthetic vitamins and minerals added back after industrial processing strips naturally occurring nutrients — a sign of heavily refined ingredients.' },
  natural_colorants:   { icon: '🎨', label: 'Natural Colorants', description: 'Plant-derived colorants (annatto, beet juice, beta-carotene, etc.) that indicate the product required color correction after processing.' },
  olive_oil_adulteration: { icon: '🫒', label: 'Olive Oil Quality', description: 'Olive oil is one of the most frequently adulterated foods on the market — even certified organic bottles are sometimes cut with cheaper oils. Worth sourcing from a brand you trust.' },
};

export default function ConcernCard({ category, flags, explanation }) {
  const [open, setOpen] = useState(false);
  const info = CATEGORY_INFO[category] || { icon: '⚠️', label: category };
  const displayExplanation = explanation || getFallbackSummary(flags);

  // Visibility only — never changes what renders. Fires once per
  // scan/category (not per open/close toggle, since `explanation` and
  // `category` don't change on that interaction) whenever the AI
  // explanation for this category was missing and the rules-engine
  // fallback summary was used instead. No ingredient text or free-form
  // content — category name only, which is a fixed enum, not PII.
  useEffect(() => {
    if (!explanation) {
      Sentry.captureMessage('[ConcernCard] AI explanation missing, using rules-engine fallback summary', {
        level: 'warning',
        tags: { route: 'concern_card', category, hasFallback: !!getFallbackSummary(flags) },
      });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [explanation, category]);
  const severity = flags.some(f => f.severity === 'reject') ? 'red' : 'yellow';
  const severityColors = { red: '#C0392B', yellow: '#D4AC0D' };
  const bgColors = { red: 'rgba(192,57,43,0.06)', yellow: 'rgba(212,172,13,0.06)' };

  return (
    <div style={{ margin: '0 16px 10px', background: 'white', border: '1.5px solid var(--cream-dark)', borderRadius: 16, overflow: 'hidden' }}>
      <div onClick={() => setOpen(!open)} style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '14px 16px', cursor: 'pointer' }}>
        <div style={{ fontSize: 20, flexShrink: 0, width: 40, height: 40, display: 'flex', alignItems: 'center', justifyContent: 'center', borderRadius: 10, background: bgColors[severity] }}>
          {info.icon}
        </div>
        <div style={{ flex: 1 }}>
          <div style={{ fontSize: 15, fontWeight: 700, color: 'var(--text-dark)', marginBottom: 2 }}>{info.label}</div>
          <div style={{ fontSize: 12, color: 'var(--text-light)', lineHeight: 1.4 }}>{flags.length} ingredient{flags.length > 1 ? 's' : ''} flagged</div>
        </div>
        <div style={{ width: 10, height: 10, borderRadius: '50%', background: severityColors[severity], flexShrink: 0 }} />
        <span style={{ fontSize: 14, color: severityColors[severity], transform: open ? 'rotate(180deg)' : 'none', transition: 'transform 0.25s' }}>▼</span>
      </div>
      {open && (
        <div style={{ padding: '0 16px 16px', borderTop: '1px solid var(--cream-dark)' }}>
          <div style={{ paddingTop: 12 }}>
            {flags.map((f, i) => (
              <span key={i} style={{ display: 'inline-block', background: bgColors[severity], borderRadius: 6, padding: '3px 8px', fontSize: 12, fontWeight: 600, color: severityColors[severity], marginRight: 6, marginBottom: 6 }}>{f.matchedIngredient}</span>
            ))}
          </div>
          {displayExplanation && <p style={{ fontSize: 14, lineHeight: 1.65, color: 'var(--text-mid)', paddingTop: 8 }}>{displayExplanation}</p>}
        </div>
      )}
    </div>
  );
}
